"""add summary table

Revision ID: 076940b65b03
Revises: 54c4aafce70a
Create Date: 2025-12-26 20:27:28.419271

"""

import sys
from pathlib import Path
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# Add the project root to the path
project_root = Path(__file__).parent.parent.parent
sys.path.insert(0, str(project_root))

from src.infrastructure.database.dao.base import UTCTimestamp  # noqa: E402


# revision identifiers, used by Alembic.
revision: str = "076940b65b03"
down_revision: Union[str, Sequence[str], None] = "54c4aafce70a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "summary",
        sa.Column(
            "created_at",
            UTCTimestamp(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("summary", "created_at")
    # ### end Alembic commands ###
