"""modify summary table

Revision ID: 715e3c32b8f5
Revises: 9c79b9723742
Create Date: 2026-01-08 22:10:39.026157

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '715e3c32b8f5'
down_revision: Union[str, Sequence[str], None] = '9c79b9723742'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_news_url', 'summary', ['url'])
    op.create_unique_constraint(None, 'summary', ['url'])                         
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'summary', type_='unique')
    op.drop_constraint('uq_news_url', 'summary', type_='unique')
    # ### end Alembic commands ###
