"""modify summary table

Revision ID: 9c79b9723742
Revises: de3f6d43f61c
Create Date: 2026-01-07 14:48:45.150384

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c79b9723742'
down_revision: Union[str, Sequence[str], None] = 'de3f6d43f61c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('summary', sa.Column('url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('summary', 'url')
    # ### end Alembic commands ###
