"""modify summary table

Revision ID: de3f6d43f61c
Revises: c82d47de36f1
Create Date: 2026-01-07 02:34:41.203513

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op
from src.infrastructure.database.dao.base import UTCTimestamp

# revision identifiers, used by Alembic.
revision: str = "de3f6d43f61c"
down_revision: Union[str, Sequence[str], None] = "c82d47de36f1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("summary", sa.Column("title", sa.String(length=200), nullable=False))
    op.add_column("summary", sa.Column("author", sa.String(length=200), nullable=False))
    op.add_column(
        "summary",
        sa.Column(
            "published_at",
            UTCTimestamp(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("summary", "published_at")
    op.drop_column("summary", "author")
    op.drop_column("summary", "title")
    # ### end Alembic commands ###
