name: Backend CD Dev

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+-dev.[0-9]+" # v1.0.0-dev.1
  workflow_dispatch:

concurrency:
  group: backend-cd-dev
  cancel-in-progress: true

jobs:
  cd:
    name: CD
    runs-on: ubuntu-latest
    env:
      AZURE_CONTAINERAPP_NAME: llm-economy-backend-dev 
      AZURE_RESOURCE_GROUP: llm-economy
      ACR_REGISTRY_NAME: devllmeconomy
      CONTAINER_NAME: llm-economy-backend-dev 
    outputs:
      imageRepository: ${{ steps.image.outputs.repository }}
      imageTag: ${{ steps.tag.outputs.tag }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Login to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ env.ACR_REGISTRY_NAME }}.azurecr.io
          username: ${{ secrets.AZURE_REGISTRY_USERNAME }}
          password: ${{ secrets.AZURE_REGISTRY_PASSWORD }}

      - name: Set tag
        id: tag
        run: |
          TAG=$(echo ${{ github.sha }} | cut -c1-8)
          echo TAG=$TAG
          echo "tag=$TAG" >> $GITHUB_OUTPUT

      - name: Set image.repository
        id: image
        run: |
          echo "repository=${{ env.ACR_REGISTRY_NAME }}.azurecr.io/llm-economy-summary" >> $GITHUB_OUTPUT

      - name: Build and push image to Azure ACR
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.image.outputs.repository }}:${{ steps.tag.outputs.tag }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Deploy to Azure Container Apps
        uses: azure/CLI@v2
        with:
          inlineScript: |
            az containerapp update \
              --name ${{ env.AZURE_CONTAINERAPP_NAME }} \
              --resource-group ${{ env.AZURE_RESOURCE_GROUP }} \
              --container-name ${{ env.CONTAINER_NAME }} \
              --image ${{ steps.image.outputs.repository }}:${{ steps.tag.outputs.tag }}
